<a href="https://colab.research.google.com/github/visalreddy/Python_Assignment/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1.How do you import the NumPy library using an alias?
import numpy as np


In [2]:
#2.How do you check the version and configuration of NumPy?
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [3]:
#3.How do you create a vector filled with zeros of size 10?
a=np.zeros(10)
c=np.zeros(10,dtype=int)
print(a)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [5]:
#5.How do you create a zero vector of size 10 with the fifth element as 1?
np.zeros(10,dtype=int)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
#6.How do you create a vector with values from 10 to 49?
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#7.How do you reverse a vector?
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
#8.How do you create a 3x3 matrix with values from 0 to 8?
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#9.How do you find indices of non-zero elements in an array?
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [10]:
#10.How do you create a 3x3 identity matrix?
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#11.How do you generate a 3x3x3 array with random values?
np.random.random((3,3,3))

array([[[0.43151109, 0.64239589, 0.97183133],
        [0.88162647, 0.39615088, 0.239605  ],
        [0.91505635, 0.38415406, 0.55267262]],

       [[0.32038627, 0.20749669, 0.24088863],
        [0.33260165, 0.18029629, 0.34117636],
        [0.86472287, 0.8763552 , 0.85572124]],

       [[0.20234779, 0.17854274, 0.12566108],
        [0.48786788, 0.81675666, 0.22258841],
        [0.49310001, 0.28887417, 0.76674641]]])

In [12]:
#12.How do you find the min and max values in a 10x10 random matrix?
x=np.random.random((10,10)).min()
y=np.random.random((10,10)).max()
print(x)
print(y)

0.001829424926732881
0.9886568743924347


In [13]:
#13.How do you calculate the mean of a random vector of size 30?
z=np.random.random(30).mean()
print(z)

0.5562943165285676


In [14]:
#14.How do you create a 2D array with 1s on the border and 0s inside?
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)


nan
False
False
nan


In [16]:
#16.How do you create a matrix with values below the diagonal?
matrix = np.tril(np.ones((4, 4)))
print(matrix)


[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [17]:
#17.How do you create a checkerboard pattern in an 8x8 matrix?
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
#18.How do you find the index of a flat element in a 3D shape?
index = np.unravel_index(100, (6, 7, 8))
print(index)

(np.int64(1), np.int64(5), np.int64(4))


In [19]:
#19.How do you create a checkerboard pattern using NumPy's tile function?
pattern = np.array([[0, 1],
                    [1, 0]])
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#20.How do you normalize a matrix (values between 0 and 1)?
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized_matrix)

[[0.81618891 1.         0.17324908 0.01557756 0.37884525]
 [0.26453778 0.31293423 0.         0.34993566 0.67167223]
 [0.74107258 0.07973365 0.76150144 0.42350735 0.66905581]
 [0.30538893 0.97972512 0.88672186 0.98906182 0.09027049]
 [0.28298945 0.41662799 0.21498157 0.39135181 0.06490547]]


In [21]:
#21.How do you define a custom data type for storing color (RGBA)?
color = np.dtype([("r",np.ubyte),
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])


In [22]:
#22.How do you perform a matrix multiplication between two matrices?
matrix1 = np.array([[1, 2],
                    [3, 4]])
matrix2 = np.array([[5, 6],
                    [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [23]:
#23.How do you negate values between two given numbers in a vector?
vector = np.arange(10)
vector[(vector >= 3) & (vector <= 8)] *= -1
print(vector)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [24]:
#24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?
print(sum(range(5), -1))
print(np.sum(range(5), -1))

9
10


In [25]:
#25.Which NumPy vector operations are legal or illegal?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#legal
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

#illegal
c = np.array([7, 8])
print(a+c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [128]:
#26.What happens when you divide integers or floats by zero in NumPy?
a = np.array([1,2,3])
b = np.array([0,0,0])
int_div = a/b
print("Integer division:",int_div)


Integer division: [inf inf inf]


/tmp/ipython-input-80607615.py:4: RuntimeWarning: divide by zero encountered in divide
  int_div = a/b


In [80]:
#27.How do you round a float array away from zero?
arr = np.array([-1.2, -1.7, 2.2, 1.3, 2.8])
rounded = np.where(arr > 0, np.ceil(arr), np.floor(arr))
print(arr)
print(rounded)

[-1.2 -1.7  2.2  1.3  2.8]
[-2. -2.  3.  2.  3.]


In [81]:
#28.How do you extract the integer part of a float using multiple methods?
arr = np.array([-1.7, -0.2, 0.9, 1.5, 2.9])
#floor
int_part = np.floor(arr)
print(int_part)
#ceil
int_part1 = np.ceil(arr)
print(int_part1)
#.astype
int_part2 = arr.astype(int)
print(int_part2)

[-2. -1.  0.  1.  2.]
[-1. -0.  1.  2.  3.]
[-1  0  0  1  2]


In [82]:
#29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
matrix=np.tile(np.arange(0,5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [84]:
#31.How do you create an array with evenly spaced values between 0 and 1 (excluded)?
print(np.linspace(0,1,12,endpoint=False))

[0.         0.08333333 0.16666667 0.25       0.33333333 0.41666667
 0.5        0.58333333 0.66666667 0.75       0.83333333 0.91666667]


In [85]:
#32.How do you sort a random array?
arr = np.random.randint(1, 20, size=10)
sorted_arr = np.sort(arr)
print("Original array:", arr)
print("Sorted array:", sorted_arr)

Original array: [ 7 10 16 10 18 11  2 12 14 11]
Sorted array: [ 2  7 10 10 11 11 12 14 16 18]


In [87]:
#33.How do you sum an array faster than using np.sum?
arr = np.array([1, 2, 3, 4, 5])
sum_arr = np.add.reduce(arr)
print(sum_arr)

15


In [86]:
#34.How do you check if two arrays are equal?
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.array_equal(arr1,arr2))

True


In [88]:
#35.How do you make a NumPy array read-only?
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False
arr[0] = 10


ValueError: assignment destination is read-only

In [89]:
#36.How do you convert Cartesian coordinates to polar coordinates?
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("radius: ",r)
print("angle: ",theta)

radius:  [1.41421356 2.82842712 4.24264069]
angle:  [0.78539816 0.78539816 0.78539816]


In [90]:
#37.How do you replace the maximum value in an array with zero?
arr = np.array([3,7,21,29,53,9])
arr[arr == arr.max()] = 0
print(arr)


[ 3  7 21 29  0  9]


In [91]:
#38.How do you create a structured array for (x, y) coordinate pairs?
coordinates = np.array([(1, 2), (3, 4), (5, 6)], dtype=[('x', int), ('y', int)])
print(coordinates)

[(1, 2) (3, 4) (5, 6)]


In [92]:
#39.How do you create a Cauchy matrix using two arrays?
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
# Create Cauchy matrix
C = 1.0 / (x[:, None] - y[None, :])
print(C)

[[-0.25       -0.2        -0.16666667 -0.14285714]
 [-0.33333333 -0.25       -0.2        -0.16666667]
 [-0.5        -0.33333333 -0.25       -0.2       ]
 [-1.         -0.5        -0.33333333 -0.25      ]]


In [93]:
#40.How do you find the range of values for each NumPy scalar type?
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min,"to",np.iinfo(dtype).max)


-128 to 127
-2147483648 to 2147483647
-9223372036854775808 to 9223372036854775807


In [94]:
#41.How do you display all values in a large array?
arr = np.arange(1000)
np.set_printoptions(threshold=np.inf)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [28]:
#42.How do you find the closest value to a given scalar in an array?
arr = np.array([1, 2, 3, 4, 5])
scalar = 2.6
closest_value = arr[np.abs(arr - scalar).argmin()]
print(closest_value)

3


In [31]:
#45.How do you cast a float array to integer type in place?
arr = np.array([1.7, 2.9, 3.2, 4.8])
arr.astype(int)
print(arr)

[1.7 2.9 3.2 4.8]


In [33]:
#47.How do you iterate through all elements in a NumPy array with indices?
arr = np.array([1, 2, 3, 4, 5])
for index, value in np.ndenumerate(arr):
  print(index,value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [34]:
#48.How do you create a 2D Gaussian-like array?
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
sigma = 0.5
# Gaussian formula
gaussian = np.exp(-(x**2+y**2)/(2*sigma**2))
print(gaussian)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

In [35]:
#49.How do you randomly place a specific number of elements in a 2D array?
arr = np.zeros((5, 5), dtype=int)
n = 5
# Get random unique positions (flattened indices)
indices = np.random.choice(arr.size, n, replace=False)
arr.flat[indices] = 1
print(arr)

[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 1]]


In [36]:
#50.How do you subtract the row mean from a matrix?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_means = np.mean(arr,axis=1,keepdims=True)
result = arr - row_means
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [37]:
#51.How do you sort a 2D array based on the values of one column?
arr = np.array([[6, 5, 4],
                [3, 2, 1],
                [9, 8, 7]])
sorted_arr = arr[arr[:, 1].argsort()]
print(sorted_arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [38]:
#52.How do you check if a 2D array contains any null (zero-only) columns?
arr = np.array([
    [0, 2, 0],
    [0, 5, 0],
    [0, 8, 0]])
null_columns = np.all(arr == 0, axis=0)
print(null_columns)


[ True False  True]


In [39]:
#53.How do you find the nearest value to a given number in a NumPy array?
arr = np.array([10, 22, 37, 41, 59])
target = 29
nearest = arr[np.abs(arr - target).argmin()]
print("Nearest value to",target,"is",nearest)

Nearest value to 29 is 22


In [40]:
#55.How do you increment elements in an array using an index array with repeats?
x = np.zeros(5,int)
indices = np.array([1,2,2,3])
np.add.at(x,indices,1)
print(x)

[0 1 2 1 0]


In [41]:
#56.How do you accumulate values into an array based on indices?
arr = np.zeros(5, dtype=int)
indices = np.array([0, 1, 2, 1, 3, 1])
values = np.array([10, 20, 30, 40, 50, 60])
np.add.at(arr, indices, values)
print(arr)

[ 10 120  30  50   0]


In [42]:
#57.How do you count unique colors in a 3D image array?
image = np.array([
    [[255, 0, 0], [0, 255, 0]],
    [[0, 0, 255], [255, 0, 0]]])
unique_colors, counts = np.unique(image.reshape(-1, image.shape[-1]), axis=0, return_counts=True)
print(unique_colors)
print(len(unique_colors))
print(counts)

[[  0   0 255]
 [  0 255   0]
 [255   0   0]]
3
[1 1 2]


In [43]:
#58.How do you compute the sum across the last two axes of a 4D array?
a = np.random.rand(1, 2, 3, 4, 5)
Results = a.sum(axis=(-2, -1))
print(Results)

[[[ 8.82031697  9.77318763 10.01652309]
  [ 9.4137348   8.70409803 11.40934569]]]


In [44]:
#59.How do you calculate means of grouped values in an array?
values = np.array([1, 2, 3, 4, 5, 6])
groups = np.array([1, 1, 2, 2, 3, 4])
means = [values[groups == g].mean() for g in np.unique(groups)]
print(means)

[np.float64(1.5), np.float64(3.5), np.float64(5.0), np.float64(6.0)]


In [45]:
#60.How do you efficiently get the diagonal of a matrix dot product?
matrix = np.array([[1, 2],
                   [3, 4]])
vector = np.array([5, 6])
result = np.dot(matrix, vector)
print(result)

[17 39]


In [47]:
#62.How do you multiply a (5,5,3) array with a (5,5) array element-wise?
A = np.random.randint(1, 10, (5, 5, 3))  # Shape (5,5,3)
B = np.random.randint(1, 10, (5, 5))     # Shape (5,5)
C = A * B[:, :, np.newaxis]
print("Result shape:", C.shape)
print(C)

Result shape: (5, 5, 3)
[[[ 7 63 56]
  [ 3  4  9]
  [ 4  6  6]
  [40 40 25]
  [49 56 21]]

 [[36 45 72]
  [16 72 56]
  [ 7 49 49]
  [63 35 21]
  [36  6 12]]

 [[ 6 16  2]
  [28 63 42]
  [20 15 25]
  [36  8 28]
  [28 16 16]]

 [[12  9 27]
  [24  6 24]
  [ 4  8  8]
  [54 18 54]
  [ 8  9  4]]

 [[21 12 15]
  [ 6 24 24]
  [54 27 27]
  [ 5  6  5]
  [20 25 10]]]


In [48]:
#63.How do you swap two rows in a matrix?
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [50]:
#65.How do you recreate an array from a bincount?
bincounts = np.array([0, 2, 1, 0, 3])
arr = np.repeat(np.arange(len(bincounts)), bincounts)
print("Bincounts:", bincounts)
print("Recreated array:", arr)

Bincounts: [0 2 1 0 3]
Recreated array: [1 1 2 4 4 4]


In [53]:
#68.How do you invert booleans or negate floats in-place?
bool_arr = np.array([True, False, True, True])
np.logical_not(bool_arr, out=bool_arr)
print("inverted Bool: ",bool_arr)

float_arr = np.array([1.2, -3.4, 5.6])
np.negative(float_arr, out=float_arr)
print("Negated Floats",float_arr)

inverted Bool:  [False  True False False]
Negated Floats [-1.2  3.4 -5.6]


In [65]:
#80.How do you extract the top N largest values from an array?
arr = np.array([10, 3, 45, 6, 23, 78, 212])
N = 5
indices = np.argpartition(arr, -N)[-N:]
top_N = arr[indices]
top_N_sorted = np.sort(top_N)[::-1]
print("Top", N, "values:", top_N_sorted)

Top 5 values: [212  78  45  23  10]


In [68]:
#83.How do you raise an array to the power of 3 using different methods?
arr = np.array([1, 2, 3, 4])
r1= np.power(arr,3)
r2= arr**3
r3= arr*arr*arr
print(r1)
print(r2)
print(r3)

[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]


In [130]:
#87.How do you extract unique rows from a 2D array?
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]])
print("Original Array:\n", A)
unique_rows = np.unique(A, axis=0)
print("\nUnique rows:\n", unique_rows)

Original Array:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique rows:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
#88.How do you compute inner, outer, sum, and multiplication using einsum?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a)
print(b)

inner = np.einsum('i,i->', a, b)
print("\nInner: ",inner)

outer = np.einsum('i,j->ij', a, b)
print("\nOuter:\n", outer)

total_sum = np.einsum('i->', a)
print("\nSum: ", total_sum)

elementwise = np.einsum('i,i->i', a, b)
print("\nMultiplication: ", elementwise)

[1 2 3]
[4 5 6]

Inner:  32

Outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Sum:  6

Multiplication:  [ 4 10 18]


In [76]:
#91.How do you vertically and horizontally stack two arrays?
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,5,4],[3,2,1]])

v_stack=np.vstack((a,b))
print("verticla stack: \n",v_stack,"\n")

h_stack=np.hstack((a,b))
print("horizpntal stac: \n",h_stack)

verticla stack: 
 [[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]] 

horizpntal stac: 
 [[1 2 3 6 5 4]
 [4 5 6 3 2 1]]


In [77]:
#92.How do you apply a custom function to each element of an array?
arr=np.array([1,2,3,4])
result=arr**2+2
print(result)

[ 3  6 11 18]


In [78]:
#93.How do you remove duplicate rows in a 2D array?
unique_rows = np.unique(arr, axis=0)
print("Unique Rows:\n", unique_rows)


Unique Rows:
 [1 2 3 4]


In [126]:
#95.How do you find column-wise and row-wise minimum/maximum indices?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_min_idx = np.argmin(arr,axis=1)
row_max_idx = np.argmax(arr,axis=1)

print("\nRow-wise minimum indices:", row_min_idx)
print("Row-wise maximum indices:", row_max_idx)




Row-wise minimum indices: [0 0 0]
Row-wise maximum indices: [2 2 2]


In [122]:
#102.How do you find the shape and number of elements in an array?
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
size = arr.size
print("Shape:", shape)
print("Size:", size)


Shape: (2, 3)
Size: 6


In [121]:
#103.How do you reshape an array without changing its data?
arr = np.array([1, 2, 3, 4, 5, 6])
new_shape = (2, 3)
reshaped_arr = arr.reshape(new_shape)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [120]:
#104.How do you flatten a multi-dimensional array?
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
flat=A.flatten()
print(flat)

B= np.arange(1,13).reshape(2,2,3)
print("\n",B,"\n")
flat2=B.ravel()
print(flat2)

[1 2 3 4 5 6]

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [110]:
#106.How do you compute element-wise maximum/minimum of two arrays?
a = np.array([1, 5, 3, 9])
b = np.array([4, 2, 8, 6])
print(np.maximum(a,b))
print(np.minimum(a,b))

[4 5 8 9]
[1 2 3 6]


In [109]:
#108.How do you transpose a matrix and perform dot products?
A = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print("Original Matrix A:\n",A)
B= A.T
print("\nTransposed Matrix Aᵀ:\n",B)
dot_prod = np.dot(A,B)
print("\nMatrix Dot Product (A·B):\n",dot_prod)

Original Matrix A:
 [[1 2 3]
 [4 5 6]]

Transposed Matrix Aᵀ:
 [[1 4]
 [2 5]
 [3 6]]

Matrix Dot Product (A·B):
 [[14 32]
 [32 77]]


In [105]:
#110.How do you extract diagonal, upper, and lower triangles from a matrix?
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print("Matrix A:\n", A)
diag = np.diag(A)
print("\nDiagonal elements:", diag)
upper = np.triu(A)
print("\nUpper triangular matrix:\n", upper)
lower = np.tril(A)
print("\nLower triangular matrix:\n", lower)



Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]

Upper triangular matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower triangular matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
